In [4]:
import numpy as np
a=np.array(range(3))
print(f'{a=},{type(a)=}')
b=np.asarray(range(6))
print(f'{b=},{type(b)=}')
c=np.array([range(3),range(5,8)])
print(f'{c=},{type(c)=}')


a=array([0, 1, 2]),type(a)=<class 'numpy.ndarray'>
b=array([0, 1, 2, 3, 4, 5]),type(b)=<class 'numpy.ndarray'>
c=array([[0, 1, 2],
       [5, 6, 7]]),type(c)=<class 'numpy.ndarray'>


In [5]:
d=np.ones((2,3))
print(f'{d=},{type(d)=}')
e=np.zeros((1,3))
print(f'{e=},{type(e)=}')


d=array([[1., 1., 1.],
       [1., 1., 1.]]),type(d)=<class 'numpy.ndarray'>
e=array([[0., 0., 0.]]),type(e)=<class 'numpy.ndarray'>


In [5]:
import numpy as np
print(f'{np.arange(3)=}')
print(f'{np.arange(2,9,2)=}')


np.arange(3)=array([0, 1, 2])
np.arange(2,9,2)=array([2, 4, 6, 8])


In [7]:
print(f'{np.linspace(3, 6,3, endpoint =True)=}')

np.linspace(3, 6,3, endpoint =True)=array([3. , 4.5, 6. ])


In [8]:
print(f'{np.logspace(1.2,3,3,base=2)=}')

np.logspace(1.2,3,3,base=2)=array([2.29739671, 4.28709385, 8.        ])


In [10]:
print(f'{np.random.uniform(49.5, 99.5)=}')

np.random.uniform(49.5, 99.5)=91.92186478963089


In [11]:
print(f'{np.random.uniform(75.5, 125.5, size=(2, 2))=}')

np.random.uniform(75.5, 125.5, size=(2, 2))=array([[87.46464181, 85.45639524],
       [78.7286159 , 96.90727448]])


In [11]:
print(f'{np.random.rand(2,3)=}')

array([[0.85314599, 0.87367872, 0.09297663],
       [0.55646254, 0.57819261, 0.20971469]])

In [12]:
import array as arr
 # creating an array with integer type
a = arr.array('i', [1, 2, 3])
 # printing original array
print ("The new created array is : ",a, end =" ")
print(f"{arr.array('i', [1, 2, 3])=}")

The new created array is :  array('i', [1, 2, 3]) arr.array('i', [1, 2, 3])=array('i', [1, 2, 3])


In [14]:
print(f"{np.array(range(3))=}")

array([0, 1, 2])

In [13]:
print(f"{np.random.rand(2,2)=}")
np.save('ok',a)
b=np.load('ok.npy')
a==b

np.random.rand(2,2)=array([[0.24271786, 0.18901889],
       [0.45103301, 0.77330935]])


array([ True,  True,  True])

In [17]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c =a*a
np.savez("ok3.npz", a, b, ok = c)
r = np.load("ok3.npz")
print(r.files) # 查看各个数组名称
print(r["arr_0"]) # 数组 a
print(r["arr_1"]) # 数组 b
print(r["ok"]) # 数组 c

['ok', 'arr_0', 'arr_1']
[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[ 1  4  9]
 [16 25 36]]


In [19]:
a=np.random.uniform(2,6,(2,2))
print(a)
np.savetxt('ok.txt',a,fmt='%f',delimiter=',')
b=np.loadtxt('ok.txt',dtype=float,delimiter=',')
print(b)

[[4.29483852 2.02508362]
 [5.72721772 2.32333821]]
[[4.294839 2.025084]
 [5.727218 2.323338]]


In [21]:
a=np.arange(1,10)
print(f'{np.arange(1,10)=}')
print(f'{a.reshape(3,3)=}')
print(f'{a.flatten()=}')
print(f'{a.ravel()=}')

np.arange(1,10)=array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.reshape(3,3)=array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
a.flatten()=array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.ravel()=array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [24]:
a.resize((4,4),refcheck=False)

In [23]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
a=np.arange(6)
b=np.expand_dims(a,axis=0)
c=np.expand_dims(a,axis=1)
print(a)
print(b)
print(c)

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [28]:
np.squeeze(b)


array([0, 1, 2, 3, 4, 5])

In [30]:
np.squeeze(c)

array([0, 1, 2, 3, 4, 5])

In [31]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
print(a,b,c,d)

[[1 2]
 [3 4]] [[5 6]
 [7 8]] [[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [32]:
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:

np.stack((a,b),1)


array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [34]:
a = np.array([[1,2,3],[4,5,6]])
np.append(a, [7,8,9])


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.append(a, [[7,8,9]],axis = 0)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.append(a, [[5,5,5],[7,8,9]],axis = 1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

In [37]:
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [38]:
np.insert(a,1,[11],axis = 0)

array([[ 1,  2,  3],
       [11, 11, 11],
       [ 4,  5,  6]])

In [39]:
np.insert(a,1,11,axis = 1)

array([[ 1, 11,  2,  3],
       [ 4, 11,  5,  6]])

In [40]:
np.broadcast_to(3,(3,3))

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [41]:
np.unique(b,return_index = True)

(array([5, 6, 7, 8]), array([0, 1, 2, 3], dtype=int64))

In [42]:
import numpy as np
a = np.arange(6).reshape(2,3)

for x in np.nditer(a):
	print (x, end=", " )

for x in np.nditer(a,order="F"):
	print(x,end=',')

for row in a:
	print(row)


0, 1, 2, 3, 4, 5, 0,3,1,4,2,5,[0 1 2]
[3 4 5]


In [43]:
for i in a.flat:
	print(i,end=',')

0,1,2,3,4,5,

In [44]:
a=np.arange(6)
np.amin(a)
np.amax(a)
np.ptp(a)
np.percentile(a,60)
np.mean(a)
np.std(a)
np.var(a)


2.9166666666666665

In [45]:
import numpy as np
aa=np.random.uniform(1,5,(2,3))
np.sort(aa)
np.argmax(aa)
np.argmin(aa)
np.where(aa>2.5)
np.extract(aa>2.5,aa)

array([3.65823768, 3.51994137, 4.21571475])